name: Deploy to EC2 (Docker)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd /home/ubuntu || exit 1

            if [ ! -d "movie_recomendation_system" ]; then
              git clone https://github.com/amit6812/movie_recomendation_system.git
            fi

            cd movie_recomendation_system
            git pull origin main

            docker stop movie-container || true
            docker rm movie-container || true
            docker rmi movie-app || true

            docker build -t movie-app .

            docker run -d \
              --name movie-container \
              -p 8501:8501 \
              movie-app
          EOF
