name: Deploy to EC2 (Docker)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }} # Ensure this matches your GitHub Secret name
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Folder check aur navigation
            cd /home/ubuntu/movie_recomendation_system || (cd /home/ubuntu && git clone https://github.com/amit6812/movie_recomendation_system.git && cd movie_recomendation_system)
            
            git pull origin main

            # Purane containers ko saaf karna
            sudo docker stop movie-container || true
            sudo docker rm movie-container || true
            sudo docker rmi movie-app || true

            # Naya image build aur run (Dono ports 8501 aur 8000 ke sath)
            sudo docker build -t movie-app .
            sudo docker run -d \
              --name movie-container \
              -p 8501:8501 \
              -p 8080:8080\
              -e TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} \
              movie-app