name: CI/CD for Movie Recommendation

on:
  push:
    branches:
      - main  # Jab aap main branch par push karenge tabhi ye chalega

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            # Purana folder delete karke naya clone karein ya update karein
            if [ -d "movie_recomendation_system" ]; then
              cd movie_recomendation_system && git pull origin main
            else
              git clone https://github.com/amit6812/movie_recomendation_system.git
              cd movie_recomendation_system
            fi
            
            # Docker Container build aur run karein
            sudo docker build -t movie-app .
            sudo docker stop movie-container || true
            sudo docker rm movie-container || true
            sudo docker run -d -p 8501:8501 -p 8000:8000 --name movie-container movie-app